2019-10-23 07:56:37,587 INFO: Cabinet startup [in /home/matrizaev/cabinet/app/__init__.py:75]
2019-10-23 08:48:41,199 INFO: Cabinet startup [in /home/matrizaev/cabinet/app/__init__.py:75]
2019-10-23 08:57:53,181 INFO: Cabinet startup [in /home/matrizaev/cabinet/app/__init__.py:75]
2019-10-23 09:06:41,783 INFO: Cabinet startup [in ./app/__init__.py:75]
2019-10-23 09:57:00,732 INFO: Cabinet startup [in ./app/__init__.py:75]
2019-10-28 11:03:18,443 INFO: Cabinet startup [in /home/matrizaev/cabinet/app/__init__.py:75]
2019-10-28 11:05:01,422 INFO: Cabinet startup [in /home/matrizaev/cabinet/app/__init__.py:75]
2019-10-28 11:05:03,272 ERROR: Exception on /orders/ [GET] [in /home/matrizaev/cabinet/venv/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/matrizaev/cabinet/venv/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/matrizaev/cabinet/venv/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/matrizaev/cabinet/venv/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/matrizaev/cabinet/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/matrizaev/cabinet/venv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/matrizaev/cabinet/venv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/matrizaev/cabinet/venv/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/matrizaev/cabinet/app/main/routes.py", line 74, in ShowOrders
    return render_template('orders.html', menuItem = 1, orders = orders, form = form)
  File "/home/matrizaev/cabinet/venv/lib/python3.6/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/home/matrizaev/cabinet/venv/lib/python3.6/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/matrizaev/cabinet/venv/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/matrizaev/cabinet/venv/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/matrizaev/cabinet/venv/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/matrizaev/cabinet/venv/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/matrizaev/cabinet/app/templates/orders.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/matrizaev/cabinet/app/templates/base.html", line 80, in top-level template code
    {% block content %}{% endblock %}
  File "/home/matrizaev/cabinet/app/templates/orders.html", line 62, in block "content"
    {% if orders | length > 0 %}
TypeError: object of type 'AppenderBaseQuery' has no len()
2019-10-28 11:07:26,169 INFO: Cabinet startup [in /home/matrizaev/cabinet/app/__init__.py:75]
2019-10-28 11:08:04,750 INFO: Cabinet startup [in /home/matrizaev/cabinet/app/__init__.py:75]
2019-10-28 11:08:42,438 INFO: Cabinet startup [in /home/matrizaev/cabinet/app/__init__.py:75]
2019-10-28 11:12:41,686 INFO: Cabinet startup [in /home/matrizaev/cabinet/app/__init__.py:75]
2019-10-28 11:12:49,005 INFO: Cabinet startup [in /home/matrizaev/cabinet/app/__init__.py:75]
2019-10-28 13:12:23,898 INFO: Cabinet startup [in /home/matrizaev/cabinet/app/__init__.py:75]
2019-10-28 13:14:59,626 INFO: Cabinet startup [in /home/matrizaev/cabinet/app/__init__.py:75]
2019-10-28 13:21:34,947 INFO: Cabinet startup [in /home/matrizaev/cabinet/app/__init__.py:75]
2019-10-28 13:23:19,348 INFO: Cabinet startup [in /home/matrizaev/cabinet/app/__init__.py:75]
2019-10-28 13:25:35,542 INFO: Cabinet startup [in /home/matrizaev/cabinet/app/__init__.py:75]
2019-10-28 13:27:16,793 INFO: Cabinet startup [in /home/matrizaev/cabinet/app/__init__.py:75]
2019-10-28 13:28:19,538 INFO: Cabinet startup [in /home/matrizaev/cabinet/app/__init__.py:75]
2019-10-28 13:30:21,643 INFO: Cabinet startup [in /home/matrizaev/cabinet/app/__init__.py:75]
2019-10-28 13:32:02,388 INFO: Cabinet startup [in /home/matrizaev/cabinet/app/__init__.py:75]
2019-10-28 13:33:58,366 INFO: Cabinet startup [in /home/matrizaev/cabinet/app/__init__.py:75]
2019-10-29 09:43:58,498 INFO: Cabinet startup [in /home/matrizaev/cabinet/app/__init__.py:75]
2019-10-29 09:44:04,523 ERROR: Exception on / [GET] [in /home/matrizaev/cabinet/venv/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/matrizaev/cabinet/venv/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/matrizaev/cabinet/venv/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/matrizaev/cabinet/venv/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/matrizaev/cabinet/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/matrizaev/cabinet/venv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/matrizaev/cabinet/venv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/matrizaev/cabinet/venv/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/matrizaev/cabinet/app/main/routes.py", line 23, in ShowIndex
    return render_template('index.html', menuItem = 0, orders = orders)
  File "/home/matrizaev/cabinet/venv/lib/python3.6/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/home/matrizaev/cabinet/venv/lib/python3.6/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/matrizaev/cabinet/venv/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/matrizaev/cabinet/venv/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/matrizaev/cabinet/venv/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/matrizaev/cabinet/venv/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/matrizaev/cabinet/app/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/matrizaev/cabinet/app/templates/base.html", line 80, in top-level template code
    {% block content %}{% endblock %}
  File "/home/matrizaev/cabinet/app/templates/index.html", line 48, in block "content"
    {% include '_order.html' %}
  File "/home/matrizaev/cabinet/app/templates/_order.html", line 6, in top-level template code
    {{ removeOrderForm.csrf_token }}
  File "/home/matrizaev/cabinet/venv/lib/python3.6/site-packages/jinja2/environment.py", line 430, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'removeOrderForm' is undefined
2019-10-29 09:45:02,059 INFO: Cabinet startup [in /home/matrizaev/cabinet/app/__init__.py:75]
2019-10-29 09:57:56,705 INFO: Cabinet startup [in /home/matrizaev/cabinet/app/__init__.py:75]
2019-10-29 09:59:52,828 INFO: Cabinet startup [in /home/matrizaev/cabinet/app/__init__.py:75]
2019-10-29 11:07:19,142 INFO: Cabinet startup [in /home/matrizaev/cabinet/app/__init__.py:75]
2019-10-29 11:09:54,677 INFO: Cabinet startup [in /home/matrizaev/cabinet/app/__init__.py:75]
2019-10-29 11:10:07,475 ERROR: Exception on /remove_order/ [POST] [in /home/matrizaev/cabinet/venv/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/matrizaev/cabinet/venv/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/matrizaev/cabinet/venv/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/matrizaev/cabinet/venv/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/matrizaev/cabinet/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/matrizaev/cabinet/venv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/matrizaev/cabinet/venv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/matrizaev/cabinet/app/main/routes.py", line 135, in RemoveOrder
    return redirect(url_for('main.ShowOrders'))
NameError: name 'url_for' is not defined
2019-10-29 11:10:54,505 INFO: Cabinet startup [in /home/matrizaev/cabinet/app/__init__.py:75]
2019-10-29 11:11:40,094 INFO: Cabinet startup [in /home/matrizaev/cabinet/app/__init__.py:75]
